### PR TITLE
[WIP] Target multiple architectures

### PR DESCRIPTION
**Pull request by Filius-Patris**
@Hyzual could you please run the pipeline? I'm not 100% sure if it works correctly. I ran it locally and I *think* it worked...

Tagging issue #21.

### CODE REVIEW

**Comment by Hyzual** [comment]
Hi, I've updated the CI workflow so that it runs on pull requests also.
It looks like `buildx` isn't supported though :/

```
docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 . --file Dockerfile --tag hyzual/koel-dev:latest
multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

**Comment by Filius-Patris** [comment]
Ah, I see. There needs to be a special "builder" (read: profile) selected. I probably did this already on my machine. If you can push to this branch, just prepend `docker buildx create --use` to the build, command, which will create and instantly use  a new builder (comparable to `git checkout -b`).

I am currently on vacation without a PC, but in ~ 2 weeks I could do it.

By the way, I forgot to mention, this will probably increase minute usage of the builds.

**Comment by Filius-Patris** [comment]
Hmm... I tired some more and almost got it working, but this error is throwing me off:
https://github.com/Filius-Patris/docker-koel/runs/910113057?check_suite_focus=true#step:5:8811

I'll be working on isolating the problem. Not on this PR though, in order to (1) not use up your build minutes 😉 and (2) not mess up your git history.

**Comment by Hyzual** [comment]
Ok thanks :smile: ! Thanks for your help !

**Comment by Filius-Patris** [comment]
# Blocked by #21 

I will close this issue for the time being, until #21 is resolved. We're blocked by the [cypress](https://github.com/cypress-io/cypress) e2e testing framewrok. See this comment: https://github.com/Hyzual/docker-koel/issues/21#issuecomment-665584321

**Pull request closed without merging**
